"""Config."""
# REMEDY_DOMAIN = "newscorp-qa-restapi.onbmc.com"
REMEDY_DOMAIN = "newscorp-restapi.onbmc.com"
REMEDY_PROTOCOL = "https"
REMEDY_USERNAME = "svc_slack"
# REMEDY_PASSWORD = "svc_slack"
REMEDY_PASSWORD = ""
SLACK_TOKEN = ""
